### ISSUE TITLE
`self` shortcode for pointing to same commentary and page

### ISSUE THREAD

**Issue by pletcher** [AjaxMultiCommentary/kodon#3]
E.g., with a comment on a line, being able to write `@[lemma](self:urn)` to create a link to a "sub-comment" on the same line.

**Comment by pletcher** [comment]
@mromanello I'm not sure that we need this to be its own feature. As it is, writing `[lemma](?glossa=urn:cts:greekLit:tlg0011.tlg003.ajmc-lj:52@lemma)` can do exactly this.

If we want the `self` to be available as a shortcut for the given passage, I'll have to find a way to make the markdown parser aware of the URN -- but I guess maybe I'm still confused about the desired behavior for this feature?

**Comment by mromanello** [comment]
Hi @pletcher, if this is the case, then I agree that we don't need the `self` shortcut. We just need a way to refer to glosses about another passage of the same text.

**Comment by pletcher** [comment]
Okay, great! This will help limit the complexity, which is always good.
