### ISSUE TITLE
Tab interface for multiple bibliographies

### ISSUE THREAD

**Issue by pletcher** [AjaxMultiCommentary/kodon#9]
- [x] Don't just stack them vertically, but rather have a different tab for each bibliography.
- [x] Allow user-defined labels in bibliography JSON

**Comment by mromanello** [comment]
@pletcher are you still planning to support multiple views on the bibliography as described [here](https://github.com/AjaxMultiCommentary/kodon/issues/8#issuecomment-2158962510)?

**Comment by pletcher** [comment]
@mromanello sorry for my delayed response. Yes, we can definitely still do that -- I think I was holding off because I couldn't get the data I needed out of WikiData yet, but I'll try again.

**Comment by mromanello** [comment]
If you want to query Wikidata to get **all publications cited by** Ferrari's commentary (`Q122238857`), this would be the query
```sparql
#defaultView:Table
SELECT 
   ?cited ?cited_authorLabel ?cited_title ?cited_pubdate
where {
  # wd:Q122238857 is the Wikidata ID for Ferrari's commentary
  wd:Q122238857 wdt:P2860 ?cited.
  ?cited wdt:P1476 ?cited_title;
         wdt:P577 ?cited_pubdate;
        wdt:P50 ?cited_author.
   
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```
[Run the query](https://w.wiki/AdTZ)

**Comment by mromanello** [comment]
If you want to see, for any publication in the AjMC bibliography, who cites it, this would be the query
```sparql
#defaultView:Table
SELECT 
   ?citing ?citing_authorLabel ?citing_title ?citing_pubdate
where {
  # wd:Q123702058 is the Wikidata ID for Bowra's _Sophoclean Tragedy_
  ?citing wdt:P2860 wd:Q123702058.
  ?citing wdt:P1476 ?citing_title;
         wdt:P577 ?citing_pubdate;
        wdt:P50 ?citing_author.
   
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```
[Run the query](https://w.wiki/AdTd)

**Comment by pletcher** [comment]
- [ ] Who is most cited in the extended bibliographies? (Does this give us a core bibliography of _Ajax_?)
